services:
  api1:
    image: mdumasl/r-backend-26-api:latest
    restart: unless-stopped
    cpuset: "0"
    environment:
      RINHA_SOCKET: /sockets/api1.sock
      RINHA_C_KD_CHROMATIC: "1"
      RINHA_C_KD_PREFETCH_DIST: "0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "160MB"

  api2:
    image: mdumasl/r-backend-26-api:latest
    restart: unless-stopped
    cpuset: "1"
    environment:
      RINHA_SOCKET: /sockets/api2.sock
      RINHA_C_KD_CHROMATIC: "1"
      RINHA_C_KD_PREFETCH_DIST: "0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "160MB"

  lb:
    image: mdumasl/r-backend-26-lb:latest
    restart: unless-stopped
    cpuset: "2,3"
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.02"
          memory: "30MB"

volumes:
  sockets:
